### ISSUE TITLE
Compiling on MacOS 11.4 fails

### ISSUE THREAD

**Issue by ihabZhaika** [mpromonet/libv4l2cpp#24]
Hey,
I am trying to compile on macOS Big Sur 11.4 and i am getting the following error:
`libv4l2cpp/inc/V4l2Device.h:18:10: fatal error: 'linux/videodev2.h' file not found
#include <linux/videodev2.h>`

@mpromonet , any suggestion on how this issue can be solved ?

**Comment by mpromonet** [comment]
Hi,

I guess you should install v4l2 includes ?

Best Regards,
Michel.

**Comment by ihabZhaika** [comment]
> v4l2

Not a macOS expert, but after lot of searching did not found any suitable library for macOS to provide the missing file, not v4l2, seems this is not available for macOS...

**Comment by mpromonet** [comment]
Hi,

v4l2 is video4linux2, this is interface to access to video. This project is wrapping this API into C++ class to simplify its usage.

If this api https://linuxtv.org/downloads/legacy/video4linux/API/V4L2_API/spec-single/v4l2.html is not supported on MacOS, this project is useless for MacOS. 

Best Regards,
Michel.

**Comment by ihabZhaika** [comment]
Ind

> Hi,
> 
> v4l2 is video4linux2, this is interface to access to video. This project is wrapping this API into C++ class to simplify its usage.
> 
> If this api https://www.kernel.org/doc/html/v4.12/media/kapi/v4l2-core.html is not supported on MacOS, this project is useless for MacOS.
> 
> Best Regards,
> Michel.

Indeed, Thanks
